name: Check translation progress

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-translation:
    runs-on: ubuntu-20.04
    name: Check translation progress
    steps:
      - uses: actions/checkout@v2
      - uses: miurahr/omegat-check-action@v0.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage: 70.0
