name: Check translation progress

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-translation:
    runs-on: ubuntu-20.04
    name: Check translation progress
    steps:
      - uses: actions/checkout@v2
      - name: make source and target directory
        run: mkdir -p source target
      - name: Prepare gradle config
        run: |
          if [[ -f build.gradle || -f build.gradle.kts ]]; then
          echo "Use existing gradle configuration."
          else
          echo "plugins { id 'org.omegat.gradle' version '1.2.5' }" > build.gradle
          fi
        shell: bash
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Generate translation
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: translate
          gradle-version: 6.7.1
          save-gradle-dependencies-cache: true
          save-generated-gradle-jars: true
      - uses: miurahr/omegat-stat@v1.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage: 70.0
